### ISSUE TITLE
Error when running default compose file on Triton

### ISSUE THREAD

**Issue by lucj** [autopilotpattern/mongodb#9]
When running the "docker-compose up" command on Triton, I have the following error that keeps on occuring:
````
 2017-03-02T10:32:01.091+0000 I NETWORK  [initandlisten] connection accepted from 192.168.128.109:43586 #33 (1 connection now open)
mongodb_1  | 2017-03-02T10:32:01.092+0000 I NETWORK  [initandlisten] connection accepted from 192.168.128.109:33255 #34 (2 connections now open)
mongodb_1  | 2017-03-02 10:32:01,096 INFO requests.packages.urllib3.connectionpool Starting new HTTP connection (1): consul
mongodb_1  | Traceback (most recent call last):
mongodb_1  |   File "/usr/local/bin/manage.py", line 441, in <module>
mongodb_1  |     if not locals()[func]():
mongodb_1  |   File "/usr/local/bin/manage.py", line 44, in wrapper
mongodb_1  |     out = apply(fn, args, kwargs)
mongodb_1  |   File "/usr/local/bin/manage.py", line 173, in health
mongodb_1  |     get_session()
mongodb_1  |   File "/usr/local/bin/manage.py", line 399, in get_session
mongodb_1  |     session_id = create_session()
mongodb_1  |   File "/usr/local/bin/manage.py", line 412, in create_session
mongodb_1  |     ttl=ttl)
mongodb_1  |   File "/usr/local/lib/python2.7/dist-packages/consul/base.py", line 1379, in create
mongodb_1  |     '/v1/session/create', params=params, data=data)
mongodb_1  |   File "/usr/local/lib/python2.7/dist-packages/consul/std.py", line 39, in put
mongodb_1  |     self.session.put(uri, data=data, verify=self.verify)))
mongodb_1  |   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 533, in put
mongodb_1  |     return self.request('PUT', url, data=data, **kwargs)
mongodb_1  |   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
mongodb_1  |     resp = self.send(prep, **send_kwargs)
mongodb_1  |   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 596, in send
mongodb_1  |     r = adapter.send(request, **kwargs)
mongodb_1  |   File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 487, in send
mongodb_1  |     raise ConnectionError(e, request=request)
mongodb_1  | requests.exceptions.ConnectionError: HTTPConnectionPool(host='consul', port=8500): Max retries exceeded with url: /v1/session/create (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7ffffd8ec790>: Failed to establish a new connection: [Errno -2] Name or service not known',))
mongodb_1  | 2017-03-02T10:32:01.627+0000 I NETWORK  [conn33] end connection 192.168.128.109:43586 (1 connection now open)
mongodb_1  | 2017-03-02T10:32:01.627+0000 I NETWORK  [conn34] end connection 192.168.128.109:33255 (1 connection now open)
mongodb_1  | 2017/03/02 10:32:01 exit status 1
````

Mongo cannot then register on consul. Any idea of what the reason could be ?

**Comment by tgross** [comment]
This error suggests that you don't have the `_env` file created with the Triton CNS name for Consul:
```
requests.exceptions.ConnectionError: HTTPConnectionPool(host='consul', port=8500)
```

See the last bit of the [config documentation](https://github.com/autopilotpattern/mongodb#configuration):

> CONSUL (optional): when using local-compose.yml, this will default to consul (and thus use the DNS provided by Docker), but for deploying on Triton via docker-compose.yml, this should be set to the CNS path of the consul service (consul.svc.XXX...)

**Comment by lucj** [comment]
Thanks @tgross, will do this.
In the future version, will it be possible to use the name of the service ("consul") without specifying the CNS path ?

**Comment by tgross** [comment]
You can set the Compose search domain (ref https://docs.docker.com/compose/compose-file/#dnssearch) to do that now, but you'll still need _some_ way to get the Triton environment information into the Compose file.

**Comment by lucj** [comment]
Thanks @tgross.
The thing that I do not really get is why the consul agent is not embedded with the application (installed in the Dockerfile alongside containerpilot binary) as this is the case in some other images.

**Comment by tgross** [comment]
It should be. Judging by the version of ContainerPilot in use here it looks like this repo needs an updating.

**Comment by lucj** [comment]
@tgross I've just done a PR for this, hope this helps.

**Comment by geek** [comment]
Fixed by https://github.com/autopilotpattern/mongodb/pull/10 I verified with an _env file on Triton
